language: node_js
node_js:
  - "10"
cache: 
  directories:  
    - node_modules

notifications:
  email:
    recipients:
      - story@nia.ac.cn
    on_success: change
    on_failure: always

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

branches:
  only:
    - master

deploy:  
  provider: pages  
  fqdn: story.nia.ac.cn
  skip-cleanup: true  
  github-token: $TOKEN
  local-dir: ./_book/ 
  target-branch: gh-pages  
  verbose: true  
  on:    
    branch: master
